### ISSUE TITLE
TestGradeHelper

### ISSUE THREAD

**Issue by ravindurra** [ravindurra/IT580Team4Lab4#5]
Let's make a new test case for GradeHelper.cs file

**Comment by sg6162eq** [comment]
it looks like a switch case where we assign it to certain game performance.

**Comment by Michaelkalsi** [comment]
Yeah i played the game...it has a health meter as the health reduces the grade also reduces and at a certain low grade the game is over

**Comment by shigau97** [comment]
okay! On it!!
Will use the 3A concept over here with file name: TestGradeHelper.cs

**Comment by ravindurra** [comment]
Let's work on it together!

**Comment by ravindurra** [comment]
![image](https://user-images.githubusercontent.com/37026958/117597949-4331e780-b10c-11eb-962c-6572fe4f4e79.png)

**Comment by shigau97** [comment]
Alright!

Creating it was a good experience and we can just follow the same suite to make more test cases.
